{% set name = "seamm-installer" %}
{% set version = "2022.7.27" %}
{% set sha256 = "73d4050bae2ee04f0fc4082f56a210f9c2df5bb8a38f0805ffc26d8e27b47d7f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fd/73/309ee4b3e70bd4d8a687d587139ba299ac22b5ee5a22f8833a249ee9bcc2/seamm-installer-2022.7.27.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - seamm-installer = seamm_installer.__main__:run

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - alembic
    - platformdirs
    - python >=3.8
    - requests
    - tabulate

test:
  imports:
    - seamm_installer
  commands:
    - pip check
    - seamm-installer --help
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_installer
  summary: The installer/updater for SEAMM (Simulation Environment for Atomistic and Molecular Simulations).
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/

extra:
  recipe-maintainers:
    - paulsaxe
