{% set name = "seamm-installer" %}
{% set version = "2022.1.10" %}
{% set sha256 = "8c89448f2de19e28898f04bb5c5353f2f4e159329257751acec988c0617ac88f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-installer/seamm-installer-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - seamm-installer = seamm_installer.__main__:run

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - platformdirs
    - python >=3.8
    - requests
    - tabulate

test:
  imports:
    - seamm_installer
  commands:
    - pip check
    - seamm-installer --help
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_installer
  summary: The installer/updater for SEAMM (Simulation Environment for Atomistic and Molecular Simulations).
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/

extra:
  recipe-maintainers:
    - paulsaxe
