{% set name = "seamm-installer" %}
{% set version = "2021.5.26" %}
{% set sha256 = "25c8e6ed4e1878b979097bc86e4cb3e3d97f9f8cce46023d91d2567ebef6dfb8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-installer/seamm-installer-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - seamm-installer = seamm_installer.__main__:run

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - requests
    - tabulate

test:
  imports:
    - seamm_installer
  commands:
    - pip check
    - seamm-installer --help
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_installer
  summary: The installer/updater for SEAMM (Simulation Environment for Atomistic and Molecular Simulations).
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/

extra:
  recipe-maintainers:
    - paulsaxe
